# Generated by Django 3.0.8 on 2020-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesrec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetails',
            name='Filter_Size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='Layers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='Learning_Rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
