# Generated by Django 3.0.8 on 2020-12-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesrec', '0003_auto_20201206_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='image',
            field=models.ImageField(upload_to='imagesrec/images'),
        ),
    ]
